import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';
import { readFileSync } from 'fs';

// Load article dates for accurate sitemap lastmod
let articleDates = {};
try {
  articleDates = JSON.parse(readFileSync('src/data/article-dates.json', 'utf-8'));
} catch {
  // File may not exist on first build, will be generated by prebuild script
}

export default defineConfig({
  site: 'https://brightinteraction.com',
  redirects: {
    // Old Webflow Swedish pages
    '/se': '/sv',
    '/se/blogg': '/sv/insights',
    '/se/tjanster': '/sv',
    '/se/om-oss': '/sv',
    '/se/kontakta-oss': '/sv',
    '/se/integritetspolicy': '/sv/privacy',
    '/se/anvandarvillkor': '/sv/terms',
    '/se/cookie-policy': '/sv/privacy',
    '/se/faq': '/sv',
    '/se/case-studies': '/sv',

    // Old Webflow English pages
    '/en': '/',
    '/en/blogg': '/insights',
    '/en/tjanster': '/',
    '/en/om-oss': '/',
    '/en/kontakta-oss': '/',
    '/en/integritetspolicy': '/privacy',
    '/en/anvandarvillkor': '/terms',
    '/en/cookie-policy': '/privacy',
    '/en/faq': '/',
    '/en/case-studies': '/',

    // Old root Swedish pages (no /se prefix)
    '/blogg': '/insights',
    '/tjanster': '/',
    '/om-oss': '/',
    '/kontakta-oss': '/',
    '/integritetspolicy': '/privacy',
    '/anvandarvillkor': '/terms',
    '/cookie-policy': '/privacy',
    '/faq': '/',
    '/case-studies': '/',
  },
  integrations: [
    tailwind(),
    sitemap({
      i18n: {
        defaultLocale: 'en',
        locales: { en: 'en', sv: 'sv' },
      },
      filter: (page) => !page.includes('/assessment') && !page.includes('/tools/'),
      serialize: (item) => {
        const url = item.url;

        // Set priority based on page type
        if (url === 'https://brightinteraction.com/' || url === 'https://brightinteraction.com/sv/') {
          item.priority = 1.0;
          item.changefreq = 'weekly';
        } else if (url.includes('/insights/') && !url.endsWith('/insights/')) {
          // Individual articles
          item.priority = 0.8;
          item.changefreq = 'monthly';
        } else if (url.endsWith('/insights/')) {
          // Insights index
          item.priority = 0.9;
          item.changefreq = 'weekly';
        } else if (url.includes('/privacy') || url.includes('/terms') || url.includes('/dpa')) {
          // Legal pages
          item.priority = 0.3;
          item.changefreq = 'yearly';
        } else {
          item.priority = 0.7;
          item.changefreq = 'monthly';
        }

        // Use real publishDate for articles, build date for other pages
        if (articleDates[url]) {
          item.lastmod = articleDates[url];
        } else {
          item.lastmod = new Date().toISOString().split('T')[0];
        }

        return item;
      },
    }),
  ],
  output: 'static',
  server: {
    host: '0.0.0.0',
    port: 4321
  },
  vite: {
    build: {
      rollupOptions: {
        output: {
          assetFileNames: '_astro/styles.[hash][extname]',
        },
      },
    },
  },
});
